name: clinical-notes
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-export=0.0.4
  - ipykernel=6.25.2
  - matplotlib=3.8.0
  - numpy=1.26.0
  - openpyxl=3.1.2
  - pandas=2.1.1
  - python=3.11.5
  - seaborn=0.12.2
