name: clinical-notes
channels:
  - defaults
dependencies:
  - matplotlib=3.8.0
  - pandas=2.1.1
  - ipykernel=6.25.2
  - python=3.11.5
  - conda-export=0.0.4
  - openpyxl=3.1.2
  - numpy=1.26.0
  - seaborn=0.12.2
  - scikit-learn
  - nltk
  - pip:
      - ecoport==0.0.1
      - pyyaml==6.0.1
      - svgling==0.3.1
      - svgwrite==1.4.3
