channels:
- defaults
- conda-forge
dependencies:
- ipykernel=6.25.0
- matplotlib=3.7.2
- nltk=3.8.1
- numpy=1.26.0
- openpyxl=3.0.10
- pandas=2.0.3
- python=3.11.5
- pyyaml=6.0
- scikit-learn=1.2.2
- seaborn=0.12.2
- pip:
  - svgling==0.4.0
  - svgwrite==1.4.3
name: clinical-notes
